"""Typer CLI: ``juncture init | compile | run | test | docs | translate``."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from juncture._version import __version__
from juncture.core.project import Project
from juncture.core.runner import DryRunReport, Runner, RunRequest
from juncture.parsers.sqlglot_parser import translate_sql

app = typer.Typer(
    name="juncture",
    help="Multi-backend SQL + Python transformation engine.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)
console = Console()
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
)


def _version_callback(value: bool) -> None:
    if value:
        console.print(f"juncture {__version__}")
        raise typer.Exit()


@app.callback(invoke_without_command=True)
def _root(
    ctx: typer.Context,
    version: bool = typer.Option(
        False,
        "--version",
        "-V",
        help="Show version and exit.",
        callback=_version_callback,
        is_eager=True,
    ),
) -> None:
    # Typer's ``no_args_is_help`` only fires when *no* flags are passed; when
    # ``--version`` is passed alone, is_eager handles the exit. Otherwise show
    # help if no subcommand was invoked.
    if ctx.invoked_subcommand is None:
        console.print(ctx.get_help())
        raise typer.Exit()


@app.command()
def init(
    path: Path = typer.Argument(Path("."), help="Target directory for the new project."),
    name: str = typer.Option("my_juncture_project", "--name", help="Project name."),
) -> None:
    """Scaffold a new Juncture project with sensible defaults."""
    path = path.resolve()
    (path / "models" / "staging").mkdir(parents=True, exist_ok=True)
    (path / "models" / "marts").mkdir(parents=True, exist_ok=True)
    (path / "tests").mkdir(parents=True, exist_ok=True)

    (path / "juncture.yaml").write_text(
        f"""name: {name}
version: 0.1.0
profile: local

default_materialization: table
default_schema: main

connections:
  local:
    type: duckdb
    path: data/{name}.duckdb
    threads: 4
"""
    )

    (path / "models" / "staging" / "stg_users.sql").write_text(
        "-- Example staging model. Replace with your data.\n"
        "SELECT 1 AS id, 'Alice' AS name UNION ALL SELECT 2, 'Bob'\n"
    )
    (path / "models" / "marts" / "user_count.sql").write_text(
        "-- Aggregate downstream of stg_users.\nSELECT COUNT(*) AS total_users FROM {{ ref('stg_users') }}\n"
    )
    (path / "models" / "schema.yml").write_text(
        """models:
  - name: stg_users
    description: Raw user records staged for downstream use.
    columns:
      - name: id
        tests: [not_null, unique]
      - name: name
        tests: [not_null]
"""
    )
    (path / "README.md").write_text(f"# {name}\n\nGenerated by `juncture init`.\n")

    console.print(
        Panel(
            f"[green]Project created at[/] {path}\n\n"
            f"Next steps:\n"
            f"  cd {path.name}\n"
            f"  juncture run\n"
            f"  juncture test",
            title="juncture init",
            border_style="green",
        )
    )


@app.command()
def compile(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    output_json: bool = typer.Option(False, "--json", help="Emit DAG as JSON."),
) -> None:
    """Parse the project, build the DAG, and show what will run."""
    project_obj = Project.load(project)
    dag = project_obj.dag()
    if output_json:
        payload = {
            "project": project_obj.config.name,
            "models": [
                {
                    "name": m.name,
                    "kind": m.kind.value,
                    "materialization": m.materialization.value,
                    "depends_on": sorted(m.depends_on),
                    "tags": m.tags,
                }
                for m in dag.models()
            ],
            "order": dag.topological_order(),
        }
        typer.echo(json.dumps(payload, indent=2))
        return

    table = Table(title=f"Juncture DAG — {project_obj.config.name}")
    table.add_column("#", justify="right", style="dim")
    table.add_column("Model")
    table.add_column("Kind")
    table.add_column("Materialization")
    table.add_column("Depends on")
    for idx, name in enumerate(dag.topological_order(), start=1):
        m = dag.model(name)
        deps = ", ".join(sorted(m.depends_on)) or "[dim]—[/]"
        table.add_row(str(idx), m.name, m.kind.value, m.materialization.value, deps)
    console.print(table)


@app.command()
def run(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    select: list[str] = typer.Option([], "--select", "-s", help="Model selectors."),
    exclude: list[str] = typer.Option([], "--exclude", "-x", help="Selectors to exclude."),
    connection: str | None = typer.Option(None, "--connection", "-c"),
    threads: int = typer.Option(4, "--threads", "-t"),
    run_tests: bool = typer.Option(False, "--test/--no-test", help="Run data tests after models."),
    full_refresh: bool = typer.Option(False, "--full-refresh"),
    var: list[str] = typer.Option([], "--var", help="key=value vars accessible as ctx.vars()."),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Print the execution plan (seeds, model layers, intra-EXECUTE layers) without touching the DB.",
    ),
    reuse_seeds: bool = typer.Option(
        False,
        "--reuse-seeds",
        help="Skip re-loading (and re-inferring types for) seeds already materialized in the target schema.",
    ),
) -> None:
    """Execute the project's DAG."""
    run_vars = dict(pair.split("=", 1) for pair in var) if var else {}
    request = RunRequest(
        project_path=project.resolve(),
        select=select,
        exclude=exclude,
        connection=connection,
        threads=threads,
        full_refresh=full_refresh,
        run_tests=run_tests,
        run_vars=run_vars,
        reuse_seeds=reuse_seeds,
    )
    if dry_run:
        plan = Runner().plan(request)
        _render_plan(plan)
        return
    report = Runner().run(request)

    table = Table(title=f"Run results — {report.project_name}")
    table.add_column("Model")
    table.add_column("Status")
    table.add_column("Rows", justify="right")
    table.add_column("Time (s)", justify="right")
    table.add_column("Error", overflow="fold")

    for r in report.models.runs:
        status_style = {"success": "green", "failed": "red", "skipped": "yellow"}[r.status]
        rows = str(r.result.row_count) if r.result and r.result.row_count is not None else "—"
        error = r.error or ""
        table.add_row(
            r.model.name,
            f"[{status_style}]{r.status}[/]",
            rows,
            f"{r.elapsed_seconds:.2f}",
            error,
        )
    console.print(table)

    if report.tests:
        tt = Table(title="Data tests")
        tt.add_column("Model")
        tt.add_column("Column")
        tt.add_column("Test")
        tt.add_column("Result")
        tt.add_column("Failing", justify="right")
        for t in report.tests:
            color = "green" if t.passed else "red"
            tt.add_row(
                t.model,
                t.column or "—",
                t.name,
                f"[{color}]{'pass' if t.passed else 'fail'}[/]",
                str(t.failing_rows),
            )
        console.print(tt)

    if not report.ok:
        raise typer.Exit(code=1)


def _render_plan(plan: DryRunReport) -> None:
    """Pretty-print a :class:`DryRunReport` for ``juncture run --dry-run``."""
    console.print(
        Panel.fit(
            f"[bold]Dry-run plan — {plan.project_name}[/]\n"
            f"[dim]No adapter is opened. Nothing is executed.[/]",
            border_style="cyan",
        )
    )

    if plan.seeds:
        console.print(f"\n[bold]Seeds[/] ({len(plan.seeds)}) — loaded in parallel before the model DAG:")
        names = ", ".join(s.name for s in plan.seeds[:10])
        if len(plan.seeds) > 10:
            names += f", ... (+{len(plan.seeds) - 10} more)"
        console.print(f"  {names}")

    console.print(f"\n[bold]Models[/] ({len(plan.models)}) — {plan.model_layers} layer(s):")
    mt = Table(show_lines=False)
    mt.add_column("Layer", justify="right")
    mt.add_column("Model")
    mt.add_column("Kind")
    mt.add_column("Materialization")
    mt.add_column("Depends on", overflow="fold")
    mt.add_column("Intra-script")
    for n in plan.models:
        intra_str = "—"
        if n.intra is not None:
            intra_str = (
                f"{n.intra.total_statements} stmts, {n.intra.layers} layer(s), "
                f"widest={n.intra.widest_layer}, parallelism={n.intra.parallelism}"
            )
        mt.add_row(
            str(n.layer),
            n.name,
            n.kind,
            n.materialization or "—",
            ", ".join(n.depends_on) or "—",
            intra_str,
        )
    console.print(mt)

    # Per-EXECUTE-model layer histogram so users can eyeball parallelism ceiling.
    for n in plan.models:
        if n.intra is None:
            continue
        console.print(f"\n[bold]{n.name}[/] intra-script layers:")
        for i, size in enumerate(n.intra.layer_sizes):
            bar = "#" * min(size, 60)
            console.print(f"  layer {i + 1:>3}: {size:>4} {bar}")


@app.command()
def test(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    select: list[str] = typer.Option([], "--select", "-s"),
    connection: str | None = typer.Option(None, "--connection", "-c"),
    threads: int = typer.Option(4, "--threads", "-t"),
) -> None:
    """Run only the data tests (assumes models are already materialized)."""
    run(
        project=project,
        select=select,
        exclude=[],
        connection=connection,
        threads=threads,
        run_tests=True,
        full_refresh=False,
        var=[],
    )


@app.command()
def docs(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    output: Path = typer.Option(Path("target/docs"), "--output", "-o"),
) -> None:
    """Emit a minimal docs JSON (lineage + columns). Full HTML docs later."""
    project_obj = Project.load(project)
    dag = project_obj.dag()
    output.mkdir(parents=True, exist_ok=True)
    manifest = {
        "project": project_obj.config.name,
        "version": project_obj.config.version,
        "models": [
            {
                "name": m.name,
                "description": m.description,
                "materialization": m.materialization.value,
                "kind": m.kind.value,
                "path": str(m.path) if m.path else None,
                "depends_on": sorted(m.depends_on),
                "tags": m.tags,
                "columns": [
                    {"name": c.name, "description": c.description, "tests": c.tests, "data_type": c.data_type}
                    for c in m.columns
                ],
            }
            for m in dag.models()
        ],
        "edges": [{"from": src, "to": tgt} for src in dag.nodes for tgt in dag.downstream(src)],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str))
    console.print(f"[green]Docs written to[/] {output / 'manifest.json'}")


@app.command()
def translate(
    sql: str = typer.Argument(..., help="SQL snippet or path to .sql file."),
    read: str = typer.Option("snowflake", "--from", "-f"),
    write: str = typer.Option("duckdb", "--to", "-t"),
) -> None:
    """Translate SQL between dialects via SQLGlot."""
    sql_text = Path(sql).read_text() if Path(sql).exists() else sql
    translated = translate_sql(sql_text, read=read, write=write)
    console.print(Panel(translated, title=f"{read} -> {write}", border_style="cyan"))


@app.command("migrate-keboola")
def migrate_keboola(
    config: Path = typer.Argument(..., help="Path to a Keboola SQL transformation config JSON."),
    output: Path = typer.Option(Path("migrated"), "--output", "-o", help="Target project directory."),
    backend: str = typer.Option("duckdb", "--backend", "-b"),
) -> None:
    """Convert a Keboola SQL transformation config into a Juncture project."""
    from juncture.migration import migrate_keboola_sql_transformation

    result = migrate_keboola_sql_transformation(
        config_json_path=config,
        target_dir=output,
        backend=backend,
    )
    table = Table(title=f"Migrated {len(result.models)} model(s) -> {result.project_path}")
    table.add_column("#", justify="right")
    table.add_column("Model")
    for i, name in enumerate(result.models, start=1):
        table.add_row(str(i), name)
    console.print(table)
    console.print(
        Panel(
            f"[green]Project at[/] {result.project_path}\n\n"
            f"Next: [bold]juncture compile --project {result.project_path}[/]",
            title="migrate-keboola",
            border_style="green",
        )
    )


@app.command("migrate-sync-pull")
def migrate_sync_pull(
    source: Path = typer.Argument(
        ...,
        help="Directory produced by kbagent sync pull, e.g. "
        "main/transformation/keboola.snowflake-transformation/<name>/",
    ),
    output: Path = typer.Option(Path("migrated-sync-pull"), "--output", "-o"),
    seeds: Path = typer.Option(
        ...,
        "--seeds",
        help="Directory with parquet seed data, as produced by "
        "`kbagent storage unload-table --file-type parquet --download`.",
    ),
    duckdb_path: str = typer.Option("data/juncture.duckdb", "--duckdb-path"),
    source_dialect: str = typer.Option(
        "snowflake",
        "--source-dialect",
        help="Source SQL dialect (snowflake, bigquery, redshift...); use 'duckdb' to skip translation.",
    ),
    target_dialect: str = typer.Option("duckdb", "--target-dialect"),
) -> None:
    """Convert a kbagent sync-pull transformation directory into a Juncture project."""
    from juncture.migration import migrate_keboola_sync_pull

    result = migrate_keboola_sync_pull(
        transformation_dir=source,
        output_dir=output,
        seeds_source=seeds,
        duckdb_path=duckdb_path,
        source_dialect=source_dialect,
        target_dialect=target_dialect,
    )
    table = Table(title=f"Migrated transformation {result.transformation_name!r}")
    table.add_column("Metric")
    table.add_column("Value", justify="right")
    table.add_row("SQL lines", f"{result.sql_line_count:,}")
    table.add_row(
        "SQL translated", f"{source_dialect} -> {target_dialect}" if result.sql_translated else "no"
    )
    table.add_row("Input seeds linked", str(result.seeds_linked))
    table.add_row("Output tables", str(len(result.output_tables)))
    table.add_row("Missing seeds", str(len(result.seeds_missing)))
    console.print(table)
    console.print(
        Panel(
            f"[green]Project at[/] {result.project_path}\n\n"
            f"Next: [bold]juncture compile --project {result.project_path}[/]",
            title="migrate-sync-pull",
            border_style="green",
        )
    )


@app.command()
def sanitize(
    project: Path = typer.Option(
        Path("."),
        "--project",
        "-p",
        help="Juncture project directory whose models/*.sql files will be re-translated in place.",
    ),
    source_dialect: str = typer.Option("snowflake", "--from-dialect"),
    target_dialect: str = typer.Option("duckdb", "--to-dialect"),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Report which files would change without writing them.",
    ),
) -> None:
    """Re-translate all ``models/*.sql`` files through ``translate_sql``.

    Intended for projects produced by an older migration pass where Snowflake
    SQL was copied verbatim and DuckDB chokes on dialect-specific constructs
    (implicit VARCHAR coercion in CASE, etc.). The same translator the migrator
    now runs by default is applied to every SQL model, statement by statement.
    """
    models_dir = project / "models"
    if not models_dir.is_dir():
        console.print(f"[red]No models/ directory at {models_dir}[/]")
        raise typer.Exit(code=1)

    table = Table(title=f"Sanitize {source_dialect} -> {target_dialect}")
    table.add_column("Model")
    table.add_column("Before", justify="right")
    table.add_column("After", justify="right")
    table.add_column("Changed", justify="center")

    changed_count = 0
    total = 0
    for sql_file in sorted(models_dir.glob("*.sql")):
        original = sql_file.read_text()
        translated = translate_sql(original, read=source_dialect, write=target_dialect)
        changed = translated != original
        total += 1
        if changed:
            changed_count += 1
        mark = "[yellow]yes[/]" if changed else "no"
        table.add_row(sql_file.name, f"{len(original):,}", f"{len(translated):,}", mark)
        if changed and not dry_run:
            sql_file.write_text(translated)

    console.print(table)
    summary = f"{changed_count}/{total} model(s) updated"
    if dry_run:
        summary += " (dry-run, nothing written)"
    console.print(Panel(summary, title="sanitize", border_style="green"))


if __name__ == "__main__":
    app()
