"""Typer CLI: ``juncture init | compile | run | test | docs | web | sql | migrate | debug``."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from juncture._version import __version__
from juncture.cli.debug_cmds import debug_app
from juncture.cli.migrate import migrate_app
from juncture.cli.sql import sql_app
from juncture.core.dag import DAG
from juncture.core.project import Project
from juncture.core.runner import DryRunReport, Runner, RunRequest

app = typer.Typer(
    name="juncture",
    help="Multi-backend SQL + Python transformation engine.",
    no_args_is_help=True,
    rich_markup_mode="rich",
)

app.add_typer(sql_app, rich_help_panel="Tools")
app.add_typer(migrate_app, rich_help_panel="Tools")
app.add_typer(debug_app, rich_help_panel="Tools")

console = Console()
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
)


def _version_callback(value: bool) -> None:
    if value:
        console.print(f"juncture {__version__}")
        raise typer.Exit()


@app.callback(invoke_without_command=True)
def _root(
    ctx: typer.Context,
    version: bool = typer.Option(
        False,
        "--version",
        "-V",
        help="Show version and exit.",
        callback=_version_callback,
        is_eager=True,
    ),
) -> None:
    # Typer's ``no_args_is_help`` only fires when *no* flags are passed; when
    # ``--version`` is passed alone, is_eager handles the exit. Otherwise show
    # help if no subcommand was invoked.
    if ctx.invoked_subcommand is None:
        console.print(ctx.get_help())
        raise typer.Exit()


# ---------------------------------------------------------------------------
# Core workflow
# ---------------------------------------------------------------------------


@app.command(rich_help_panel="Core workflow")
def init(
    path: Path = typer.Argument(Path("."), help="Target directory for the new project."),
    name: str = typer.Option("my_juncture_project", "--name", help="Project name."),
) -> None:
    """Scaffold a new Juncture project with sensible defaults."""
    path = path.resolve()
    (path / "models" / "staging").mkdir(parents=True, exist_ok=True)
    (path / "models" / "marts").mkdir(parents=True, exist_ok=True)
    (path / "tests").mkdir(parents=True, exist_ok=True)

    (path / "juncture.yaml").write_text(
        f"""name: {name}
version: 0.1.0
profile: local

default_materialization: table
default_schema: main

connections:
  local:
    type: duckdb
    path: data/{name}.duckdb
    threads: 4
"""
    )

    (path / "models" / "staging" / "stg_users.sql").write_text(
        "-- Example staging model. Replace with your data.\n"
        "SELECT 1 AS id, 'Alice' AS name UNION ALL SELECT 2, 'Bob'\n"
    )
    (path / "models" / "marts" / "user_count.sql").write_text(
        "-- Aggregate downstream of stg_users.\nSELECT COUNT(*) AS total_users FROM {{ ref('stg_users') }}\n"
    )
    (path / "models" / "schema.yml").write_text(
        """models:
  - name: stg_users
    description: Raw user records staged for downstream use.
    columns:
      - name: id
        tests: [not_null, unique]
      - name: name
        tests: [not_null]
"""
    )
    (path / "README.md").write_text(f"# {name}\n\nGenerated by `juncture init`.\n")

    console.print(
        Panel(
            f"[green]Project created at[/] {path}\n\n"
            f"Next steps:\n"
            f"  cd {path.name}\n"
            f"  juncture run\n"
            f"  juncture test",
            title="juncture init",
            border_style="green",
        )
    )


@app.command(rich_help_panel="Core workflow")
def compile(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    output_json: bool = typer.Option(False, "--json", help="Emit DAG as JSON."),
    dot: Path | None = typer.Option(
        None,
        "--dot",
        help="Write the DAG as a Graphviz DOT file. Render with `dot -Tsvg <file> > <file>.svg`.",
    ),
) -> None:
    """Parse the project, build the DAG, and show what will run."""
    project_obj = Project.load(project)
    dag = project_obj.dag()
    if output_json:
        payload = {
            "project": project_obj.config.name,
            "models": [
                {
                    "name": m.name,
                    "kind": m.kind.value,
                    "materialization": m.materialization.value,
                    "depends_on": sorted(m.depends_on),
                    "tags": m.tags,
                    "disabled": m.disabled,
                }
                for m in dag.models()
            ],
            "order": dag.topological_order(),
        }
        typer.echo(json.dumps(payload, indent=2))
        return

    if dot is not None:
        dot.parent.mkdir(parents=True, exist_ok=True)
        _write_dag_dot(dag, dot, project_name=project_obj.config.name)
        console.print(
            f"[green]Wrote Graphviz DOT to[/] {dot}\n"
            f"Render with: [bold]dot -Tsvg {dot} > {dot.with_suffix('.svg')}[/]\n"
            f"For a denser layout on large DAGs try: "
            f"[bold]sfdp -Tsvg -Goverlap=prism {dot} > {dot.with_suffix('.svg')}[/]"
        )
        return

    table = Table(title=f"Juncture DAG — {project_obj.config.name}")
    table.add_column("#", justify="right", style="dim")
    table.add_column("Model")
    table.add_column("Kind")
    table.add_column("Materialization")
    table.add_column("Depends on")
    for idx, name in enumerate(dag.topological_order(), start=1):
        m = dag.model(name)
        deps = ", ".join(sorted(m.depends_on)) or "[dim]—[/]"
        table.add_row(str(idx), m.name, m.kind.value, m.materialization.value, deps)
    console.print(table)


_DOT_COLOR = {
    "seed": "#FFE8C8",  # warm amber — pre-DAG input
    "sql": "#CFE8F5",  # cool blue — SQL transform
    "python": "#D6F0D6",  # soft green — Python transform
}


def _write_dag_dot(dag: DAG, path: Path, *, project_name: str) -> None:
    """Write ``dag`` as a Graphviz DOT file with colour-coded nodes by kind."""
    lines: list[str] = [
        f'digraph "{project_name}" {{',
        "  rankdir=LR;",
        "  graph [nodesep=0.2, ranksep=0.6, splines=ortho];",
        '  node  [shape=box, style="filled,rounded", fontname="Helvetica", fontsize=10];',
        "  edge  [arrowsize=0.5, color=gray40];",
    ]
    for name in dag.topological_order():
        m = dag.model(name)
        color = _DOT_COLOR.get(m.kind.value, "#FFFFFF")
        label = m.name.replace('"', '\\"') + f"\\n[{m.kind.value}/{m.materialization.value}]"
        lines.append(f'  "{m.name}" [label="{label}", fillcolor="{color}"];')
    for name in dag.topological_order():
        m = dag.model(name)
        for dep in sorted(m.depends_on):
            lines.append(f'  "{dep}" -> "{m.name}";')
    lines.append("}")
    path.write_text("\n".join(lines))


@app.command(rich_help_panel="Core workflow")
def run(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    select: list[str] = typer.Option([], "--select", "-s", help="Model selectors."),
    exclude: list[str] = typer.Option([], "--exclude", "-x", help="Selectors to exclude."),
    connection: str | None = typer.Option(None, "--connection", "-c"),
    threads: int = typer.Option(4, "--threads", "-t"),
    run_tests: bool = typer.Option(False, "--test/--no-test", help="Run data tests after models."),
    full_refresh: bool = typer.Option(False, "--full-refresh"),
    var: list[str] = typer.Option([], "--var", help="key=value vars accessible as ctx.vars()."),
    dry_run: bool = typer.Option(
        False,
        "--dry-run",
        help="Print the execution plan (seeds, model layers, intra-EXECUTE layers) without touching the DB.",
    ),
    reuse_seeds: bool = typer.Option(
        False,
        "--reuse-seeds",
        help="Skip re-loading (and re-inferring types for) seeds already materialized in the target schema.",
    ),
    parallelism: int | None = typer.Option(
        None,
        "--parallelism",
        "-P",
        help="Override config.parallelism on every EXECUTE model (for benchmarking "
        "without editing schema.yml). Default: respect per-model config.",
    ),
    continue_on_error: bool = typer.Option(
        False,
        "--continue-on-error",
        help="For EXECUTE materializations: keep running after a failing statement "
        "and collect every primary error into the run report. Intended for migration "
        "triage — pair with `juncture debug diagnostics` to classify the errors.",
    ),
    disable: list[str] = typer.Option(
        [],
        "--disable",
        help="Comma-separated model names to disable for this run. Disabled models "
        "are reported as status=disabled and their downstream as skipped "
        "(upstream_disabled); the run does not fail.",
    ),
    enable_only: list[str] = typer.Option(
        [],
        "--enable-only",
        help="Inverse of --disable: disable every model not in this list.",
    ),
) -> None:
    """Execute the project's DAG."""
    run_vars = dict(pair.split("=", 1) for pair in var) if var else {}
    disable_flat = [x.strip() for item in disable for x in item.split(",") if x.strip()]
    enable_only_flat = [x.strip() for item in enable_only for x in item.split(",") if x.strip()]
    request = RunRequest(
        project_path=project.resolve(),
        select=select,
        exclude=exclude,
        connection=connection,
        threads=threads,
        full_refresh=full_refresh,
        run_tests=run_tests,
        run_vars=run_vars,
        reuse_seeds=reuse_seeds,
        parallelism_override=parallelism,
        continue_on_error=continue_on_error,
        disable_models=disable_flat,
        enable_only=enable_only_flat if enable_only_flat else None,
    )
    if dry_run:
        plan = Runner().plan(request)
        _render_plan(plan)
        return
    report = Runner().run(request)

    table = Table(title=f"Run results — {report.project_name}")
    table.add_column("Model")
    table.add_column("Status")
    table.add_column("Rows", justify="right")
    table.add_column("Time (s)", justify="right")
    table.add_column("Error", overflow="fold")

    status_colors = {
        "success": "green",
        "failed": "red",
        "skipped": "yellow",
        "partial": "yellow",
        "disabled": "dim",
    }
    for r in report.models.runs:
        status_style = status_colors.get(r.status, "white")
        rows = str(r.result.row_count) if r.result and r.result.row_count is not None else "—"
        error = r.error or ""
        table.add_row(
            r.model.name,
            f"[{status_style}]{r.status}[/]",
            rows,
            f"{r.elapsed_seconds:.2f}",
            error,
        )
    console.print(table)

    # Per-statement errors from continue-on-error runs. Printed after the
    # main results table so they don't crowd the overview. First three
    # errors verbatim, plus a count of the rest — migration triage uses
    # `juncture debug diagnostics` on the full list anyway.
    for r in report.models.runs:
        if not (r.result and r.result.statement_errors):
            continue
        errors = r.result.statement_errors
        console.print(
            f"\n[bold yellow]{r.model.name}[/] — {len(errors)} statement(s) failed (continue-on-error):"
        )
        for err in errors[:3]:
            layer_tag = f" layer={err.layer}" if err.layer is not None else ""
            console.print(f"  [dim]#{err.index}{layer_tag}[/] {err.error}")
        if len(errors) > 3:
            console.print(f"  [dim]... +{len(errors) - 3} more[/]")

    if report.tests:
        tt = Table(title="Data tests")
        tt.add_column("Model")
        tt.add_column("Column")
        tt.add_column("Test")
        tt.add_column("Result")
        tt.add_column("Failing", justify="right")
        for t in report.tests:
            color = "green" if t.passed else "red"
            tt.add_row(
                t.model,
                t.column or "—",
                t.name,
                f"[{color}]{'pass' if t.passed else 'fail'}[/]",
                str(t.failing_rows),
            )
        console.print(tt)

    if not report.ok:
        raise typer.Exit(code=1)


def _render_plan(plan: DryRunReport) -> None:
    """Pretty-print a :class:`DryRunReport` for ``juncture run --dry-run``."""
    console.print(
        Panel.fit(
            f"[bold]Dry-run plan — {plan.project_name}[/]\n"
            f"[dim]No adapter is opened. Nothing is executed.[/]",
            border_style="cyan",
        )
    )

    if plan.seeds:
        console.print(f"\n[bold]Seeds[/] ({len(plan.seeds)}) — loaded in parallel before the model DAG:")
        names = ", ".join(s.name for s in plan.seeds[:10])
        if len(plan.seeds) > 10:
            names += f", ... (+{len(plan.seeds) - 10} more)"
        console.print(f"  {names}")

    console.print(f"\n[bold]Models[/] ({len(plan.models)}) — {plan.model_layers} layer(s):")
    mt = Table(show_lines=False)
    mt.add_column("Layer", justify="right")
    mt.add_column("Model")
    mt.add_column("Kind")
    mt.add_column("Materialization")
    mt.add_column("Depends on", overflow="fold")
    mt.add_column("Intra-script")
    for n in plan.models:
        intra_str = "—"
        if n.intra is not None:
            intra_str = (
                f"{n.intra.total_statements} stmts, {n.intra.layers} layer(s), "
                f"widest={n.intra.widest_layer}, parallelism={n.intra.parallelism}"
            )
        mt.add_row(
            str(n.layer),
            n.name,
            n.kind,
            n.materialization or "—",
            ", ".join(n.depends_on) or "—",
            intra_str,
        )
    console.print(mt)

    for n in plan.models:
        if n.intra is None:
            continue
        console.print(f"\n[bold]{n.name}[/] intra-script layers:")
        for i, size in enumerate(n.intra.layer_sizes):
            bar = "#" * min(size, 60)
            console.print(f"  layer {i + 1:>3}: {size:>4} {bar}")


@app.command(rich_help_panel="Core workflow")
def test(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    select: list[str] = typer.Option([], "--select", "-s"),
    connection: str | None = typer.Option(None, "--connection", "-c"),
    threads: int = typer.Option(4, "--threads", "-t"),
) -> None:
    """Run only the data tests (assumes models are already materialized)."""
    request = RunRequest(
        project_path=project.resolve(),
        select=select,
        connection=connection,
        threads=threads,
        run_tests=True,
    )
    report = Runner().run(request)

    if report.tests:
        tt = Table(title="Data tests")
        tt.add_column("Model")
        tt.add_column("Column")
        tt.add_column("Test")
        tt.add_column("Result")
        tt.add_column("Failing", justify="right")
        for t in report.tests:
            color = "green" if t.passed else "red"
            tt.add_row(
                t.model,
                t.column or "—",
                t.name,
                f"[{color}]{'pass' if t.passed else 'fail'}[/]",
                str(t.failing_rows),
            )
        console.print(tt)
    else:
        console.print("[dim]No data tests found.[/]")

    if not report.ok:
        raise typer.Exit(code=1)


@app.command(rich_help_panel="Core workflow")
def docs(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    output: Path = typer.Option(Path("target/docs"), "--output", "-o"),
) -> None:
    """Emit a minimal docs JSON (lineage + columns). Full HTML docs later."""
    project_obj = Project.load(project)
    dag = project_obj.dag()
    output.mkdir(parents=True, exist_ok=True)
    manifest = {
        "project": project_obj.config.name,
        "version": project_obj.config.version,
        "models": [
            {
                "name": m.name,
                "description": m.description,
                "materialization": m.materialization.value,
                "kind": m.kind.value,
                "path": str(m.path) if m.path else None,
                "depends_on": sorted(m.depends_on),
                "tags": m.tags,
                "columns": [
                    {"name": c.name, "description": c.description, "tests": c.tests, "data_type": c.data_type}
                    for c in m.columns
                ],
            }
            for m in dag.models()
        ],
        "edges": [{"from": src, "to": tgt} for src in dag.nodes for tgt in dag.downstream(src)],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str))
    console.print(f"[green]Docs written to[/] {output / 'manifest.json'}")


@app.command(rich_help_panel="Core workflow")
def web(
    project: Path = typer.Option(Path("."), "--project", "-p", help="Project directory."),
    host: str = typer.Option("127.0.0.1", "--host", help="Bind address."),
    port: int = typer.Option(8765, "--port", help="Bind port."),
) -> None:
    """Serve the DAG + run history via a local HTTP server.

    Read-only single-page UI: DAG visualisation (cytoscape.js) plus
    run history. Reads ``<project>/target/run_history.jsonl`` for
    the history view — populated every time ``juncture run`` finishes.

    Binds to 127.0.0.1 by default. Ctrl-C stops.
    """
    from juncture.web.server import serve

    project_path = project.resolve()
    if not (project_path / "juncture.yaml").exists():
        console.print(f"[red]No juncture.yaml at {project_path}[/]")
        raise typer.Exit(code=1)
    console.print(
        Panel(
            f"[green]Serving[/] {project_path.name}\n"
            f"Open [bold]http://{host}:{port}[/] in your browser.\n"
            f"[dim]Ctrl-C to stop.[/]",
            title="juncture web",
            border_style="green",
        )
    )
    serve(project_path, host=host, port=port)


# ---------------------------------------------------------------------------
# Deprecated aliases — kept for backwards compatibility with scripts that
# use the old flat command names. Hidden from --help; print a deprecation
# warning at runtime. Will be removed in a future minor release.
# ---------------------------------------------------------------------------


@app.command("translate", hidden=True, deprecated=True)
def _compat_translate(
    sql: str = typer.Argument(..., help="SQL snippet or path to .sql file."),
    read: str = typer.Option("snowflake", "--from", "-f"),
    write: str = typer.Option("duckdb", "--to", "-t"),
) -> None:
    """Deprecated: use ``juncture sql translate`` instead."""
    from juncture.cli.sql import translate as _impl

    _impl(sql=sql, read=read, write=write)


@app.command("sanitize", hidden=True, deprecated=True)
def _compat_sanitize(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    source_dialect: str = typer.Option("snowflake", "--from-dialect"),
    target_dialect: str = typer.Option("duckdb", "--to-dialect"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    schema_aware: bool = typer.Option(True, "--schema-aware/--no-schema-aware"),
) -> None:
    """Deprecated: use ``juncture sql sanitize`` instead."""
    from juncture.cli.sql import sanitize as _impl

    _impl(
        project=project,
        source_dialect=source_dialect,
        target_dialect=target_dialect,
        dry_run=dry_run,
        schema_aware=schema_aware,
    )


@app.command("split-execute", hidden=True, deprecated=True)
def _compat_split_execute(
    sql_path: Path = typer.Argument(...),
    out_dir: Path = typer.Option(..., "--out", "-o"),
    source_dialect: str = typer.Option("duckdb", "--source-dialect"),
    dry_run: bool = typer.Option(False, "--dry-run"),
) -> None:
    """Deprecated: use ``juncture sql split`` instead."""
    from juncture.cli.sql import split as _impl

    _impl(sql_path=sql_path, out_dir=out_dir, source_dialect=source_dialect, dry_run=dry_run)


@app.command("migrate-keboola", hidden=True, deprecated=True)
def _compat_migrate_keboola(
    config: Path = typer.Argument(...),
    output: Path = typer.Option(Path("migrated"), "--output", "-o"),
    backend: str = typer.Option("duckdb", "--backend", "-b"),
) -> None:
    """Deprecated: use ``juncture migrate keboola`` instead."""
    from juncture.cli.migrate import keboola as _impl

    _impl(config=config, output=output, backend=backend)


@app.command("migrate-sync-pull", hidden=True, deprecated=True)
def _compat_migrate_sync_pull(
    source: Path = typer.Argument(...),
    output: Path = typer.Option(Path("migrated-sync-pull"), "--output", "-o"),
    seeds: Path = typer.Option(..., "--seeds"),
    duckdb_path: str = typer.Option("data/juncture.duckdb", "--duckdb-path"),
    source_dialect: str = typer.Option("snowflake", "--source-dialect"),
    target_dialect: str = typer.Option("duckdb", "--target-dialect"),
    validate: bool = typer.Option(False, "--validate"),
) -> None:
    """Deprecated: use ``juncture migrate sync-pull`` instead."""
    from juncture.cli.migrate import sync_pull as _impl

    _impl(
        source=source,
        output=output,
        seeds=seeds,
        duckdb_path=duckdb_path,
        source_dialect=source_dialect,
        target_dialect=target_dialect,
        validate=validate,
    )


@app.command("diagnostics", hidden=True, deprecated=True)
def _compat_diagnostics(
    project: Path = typer.Option(Path("."), "--project", "-p"),
    select: list[str] = typer.Option([], "--select", "-s"),
    connection: str | None = typer.Option(None, "--connection", "-c"),
    threads: int = typer.Option(4, "--threads", "-t"),
    show_fixes: bool = typer.Option(True, "--show-fixes/--no-show-fixes"),
) -> None:
    """Deprecated: use ``juncture debug diagnostics`` instead."""
    from juncture.cli.debug_cmds import diagnostics as _impl

    _impl(
        project=project,
        select=select,
        connection=connection,
        threads=threads,
        show_fixes=show_fixes,
    )


if __name__ == "__main__":
    app()
